### ISSUE TITLE
:shield: Security vulnerabilities

### ISSUE THREAD

**Issue by hitisec** [A3h1nt/Grawler#7]
Hi, 
Some potential security vulnerabilities has been identified in this repository.
Please Validate reports submitted on huntr and if are valid please mark them valid there.
The report links are the following:  

https://huntr.dev/bounties/f2db0c7f-5b4c-4ebc-aa3b-b6e073b5212d/
https://huntr.dev/bounties/90ead28c-588e-4a42-bdea-771151d1b279/
https://huntr.dev/bounties/d62a70c7-9164-4888-b63a-e75c2299618d/

**Comment by A3h1nt** [comment]
I've validated them, congratulations !
